import 'package:freezed_annotation/freezed_annotation.dart';

import '../../domain/entities/market_index.dart';

part 'market_index_model.freezed.dart';
part 'market_index_model.g.dart';

/// Data model representing a market index from external sources (API/Database).
///
/// This model is part of the Data layer and handles JSON serialization/deserialization.
/// It extends the domain [MarketIndex] entity concept but includes additional
/// fields or transformations needed for data mapping.
///
/// The model uses Freezed for immutable data classes and json_serializable
/// for automatic JSON parsing. This ensures type safety and reduces boilerplate.
///
/// To convert this model to a domain entity, use the [toEntity] method.
/// This separation ensures the Domain layer remains independent of data sources.
@freezed
class MarketIndexModel with _$MarketIndexModel {
  /// Creates a new [MarketIndexModel] instance.
  const factory MarketIndexModel({
    /// The display name of the index (e.g., "Nifty 50", "S&P BSE Sensex").
    required String name,

    /// The ticker symbol or short code (e.g., "NIFTY", "SENSEX").
    required String symbol,

    /// The current value of the index.
    required double value,

    /// The absolute change in the index value from the previous close.
    required double change,

    /// The percentage change from the previous close.
    required double changePercent,

    /// Optional historical data points for rendering a sparkline chart.
    @Default(null) List<double>? sparklineData,
  }) = _MarketIndexModel;

  /// Creates a [MarketIndexModel] from a JSON map.
  ///
  /// This factory method is generated by json_serializable and handles
  /// automatic parsing of JSON data from API responses or local storage.
  factory MarketIndexModel.fromJson(Map<String, dynamic> json) =>
      _$MarketIndexModelFromJson(json);
}

/// Extension methods for [MarketIndexModel] to convert to domain entities.
extension MarketIndexModelExtension on MarketIndexModel {
  /// Converts this data model to a domain [MarketIndex] entity.
  ///
  /// This method maps the data layer model to the domain layer entity,
  /// ensuring clean separation of concerns. The domain entity should be
  /// used throughout the application layers except for data serialization.
  MarketIndex toEntity() {
    return MarketIndex(
      name: name,
      symbol: symbol,
      value: value,
      change: change,
      changePercent: changePercent,
      sparklineData: sparklineData,
    );
  }
}