import 'package:freezed_annotation/freezed_annotation.dart';

import '../../domain/entities/stock.dart';

part 'stock_model.freezed.dart';
part 'stock_model.g.dart';

/// Data model representing a stock from external sources (API/Database).
///
/// This model is part of the Data layer and handles JSON serialization/deserialization.
/// It uses Freezed for immutable data classes and json_serializable for automatic
/// JSON parsing, ensuring type safety and reducing boilerplate.
///
/// To convert this model to a domain entity, use the [toEntity] method.
/// This separation ensures the Domain layer remains independent of data sources.
@freezed
class StockModel with _$StockModel {
  /// Creates a new [StockModel] instance.
  const factory StockModel({
    /// The stock ticker symbol (e.g., "RELIANCE", "TCS").
    required String symbol,

    /// The full name of the company.
    required String companyName,

    /// The current market price (Last Traded Price).
    required double currentPrice,

    /// The absolute change in price from the previous close.
    required double change,

    /// The percentage change from the previous close.
    required double changePercent,

    /// The total trading volume.
    required double volume,

    /// The market capitalization of the company (in INR).
    @Default(null) double? marketCap,

    /// The 52-week high price.
    @Default(null) double? high52Week,

    /// The 52-week low price.
    @Default(null) double? low52Week,

    /// Optional historical data points for a sparkline chart.
    @Default(null) List<double>? sparklineData,
  }) = _StockModel;

  /// Creates a [StockModel] from a JSON map.
  ///
  /// Generated by json_serializable to handle automatic parsing of JSON data
  /// from API responses or local storage.
  factory StockModel.fromJson(Map<String, dynamic> json) =>
      _$StockModelFromJson(json);
}

/// Extension methods for [StockModel] to convert to domain entities.
extension StockModelExtension on StockModel {
  /// Converts this data model to a domain [Stock] entity.
  ///
  /// Maps the data layer model to the domain layer entity, ensuring clean
  /// separation of concerns. The domain entity should be used throughout
  /// the application layers except for data serialization.
  Stock toEntity() {
    return Stock(
      symbol: symbol,
      companyName: companyName,
      currentPrice: currentPrice,
      change: change,
      changePercent: changePercent,
      volume: volume,
      marketCap: marketCap,
      high52Week: high52Week,
      low52Week: low52Week,
      sparklineData: sparklineData,
    );
  }
}