import 'package:freezed_annotation/freezed_annotation.dart';

import '../../domain/entities/holding.dart';

part 'holding_model.freezed.dart';
part 'holding_model.g.dart';

/// Data model representing a portfolio holding from external sources (API/Database).
///
/// This model is part of the Data layer and handles JSON serialization/deserialization.
/// It uses Freezed for immutable data classes and json_serializable for automatic
/// JSON parsing, ensuring type safety and reducing boilerplate.
///
/// To convert this model to a domain entity, use the [toEntity] method.
/// This separation ensures the Domain layer remains independent of data sources.
@freezed
class HoldingModel with _$HoldingModel {
  /// Creates a new [HoldingModel] instance.
  const factory HoldingModel({
    /// The stock ticker symbol (e.g., "RELIANCE", "TCS").
    required String symbol,

    /// The full name of the company.
    required String companyName,

    /// The number of shares held.
    required double quantity,

    /// The average purchase price per share.
    required double avgBuyPrice,

    /// The current market price per share.
    required double currentPrice,
  }) = _HoldingModel;

  /// Creates a [HoldingModel] from a JSON map.
  ///
  /// Generated by json_serializable to handle automatic parsing of JSON data
  /// from API responses or local storage.
  factory HoldingModel.fromJson(Map<String, dynamic> json) =>
      _$HoldingModelFromJson(json);
}

/// Extension methods for [HoldingModel] to convert to domain entities.
extension HoldingModelExtension on HoldingModel {
  /// Converts this data model to a domain [Holding] entity.
  ///
  /// Maps the data layer model to the domain layer entity, ensuring clean
  /// separation of concerns. The domain entity should be used throughout
  /// the application layers except for data serialization.
  Holding toEntity() {
    return Holding(
      symbol: symbol,
      companyName: companyName,
      quantity: quantity,
      avgBuyPrice: avgBuyPrice,
      currentPrice: currentPrice,
    );
  }
}